### ISSUE TITLE
GitList crash if there are no repository

### ISSUE THREAD

**Issue by loclamor** [klaussilveira/gitlist#427]
In apache logs, there is the following message : 

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'There are no GIT repositories in /var/gi
t/' in /var/www/gitlist/src/GitList/Git/Client.php:41\nStack trace:\n#0 /var/www/gitlist/src/GitList/Util/Routing.php(115): GitList\\Git\\Client->getRepositories(Array)\n#1 /var/www/gitlist/src/Gi
tList/Controller/MainController.php(48): GitList\\Util\\Routing->getRepositoryRegex()\n#2 /var/www/gitlist/vendor/silex/silex/src/Silex/Application.php(458): GitList\\Controller\\MainController->c
onnect(Object(GitList\\Application))\n#3 /var/www/gitlist/boot.php(7): Silex\\Application->mount('', Object(GitList\\Controller\\MainController))\n#4 /var/www/gitlist/index.php(24): require('/var/
www/gitlis...')\n#5 {main}\n  thrown in /var/www/gitlist/src/GitList/Git/Client.php on line 41
```

Perhaps catch the error and display an error message will be more user-friendly

**Comment by afranke** [comment]
This is linked to bug #396.
