### ISSUE TITLE
Commit page: Class 'SimpleXmlIterator' not found

### ISSUE THREAD

**Issue by Ymil** [klaussilveira/gitlist#791]
In the moment entry in commit page my navegator get a 500 error, to the see the apache error.log,  i find with next menssage:

`PHP Fatal error:  Uncaught Error: Class 'SimpleXmlIterator' not found in /var/www/gitlist/vendor/klaussilveira/gitter/lib/Gitter/PrettyFormat.php:22\nStack trace:\n#0 /var/www/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Repository.php(586): Gitter\\PrettyFormat->parse('<item><hash>bbe...')\n#1 /var/www/gitlist/src/Git/Repository.php(276): Gitter\\Repository->getPrettyFormat('log --skip=0 --...')\n#2 /var/www/gitlist/src/Controller/CommitController.php(39): GitList\\Git\\Repository->getPaginatedCommits('master', 0)\n#3 [internal function]: GitList\\Controller\\CommitController->GitList\\Controller\\{closure}(Object(Symfony\\Component\\HttpFoundation\\Request), 'opencv-ocr', 'master')\n#4 /var/www/gitlist/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Object(Closure), Array)\n#5 /var/www/gitlist/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#6 /var/www/gitlist/vendor/silex/silex/src/Silex/Application.php(586): Symfony\\ in /var/www/gitlist/vendor/klaussilveira/gitter/lib/Gitter/PrettyFormat.php on line 22, referer: http://192.168.1.2/gitlist/opencv-ocr/stats/master
`

In the debian jessie, this it resolve with installing php-simplexml:
`root@server:/var/www/gitlist# sudo aptitude install php-simplexml
Note: selecting "php7.0-xml" instead of the virtual package "php-simplexml"
Se instalarán los siguiente paquetes NUEVOS:
  libxslt1.1{a} php7.0-xml
0 paquetes actualizados, 2 nuevos instalados, 0 para eliminar y 0 sin actualizar.
Necesito descargar 346 kB de ficheros. Después de desempaquetar se usarán 980 kB.
¿Quiere continuar? [Y/n/?] Y
Des: 1 http://deb.debian.org/debian stretch/main amd64 libxslt1.1 amd64 1.1.29-2.1 [233 kB]
Des: 2 http://deb.debian.org/debian stretch/main amd64 php7.0-xml amd64 7.0.27-0+deb9u1 [112 kB]
Descargados 346 kB en 0s (394 kB/s)
Seleccionando el paquete libxslt1.1:amd64 previamente no seleccionado.
(Leyendo la base de datos ... 27893 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../libxslt1.1_1.1.29-2.1_amd64.deb ...
Desempaquetando libxslt1.1:amd64 (1.1.29-2.1) ...
Seleccionando el paquete php7.0-xml previamente no seleccionado.
Preparando para desempaquetar .../php7.0-xml_7.0.27-0+deb9u1_amd64.deb ...
Desempaquetando php7.0-xml (7.0.27-0+deb9u1) ...
Procesando disparadores para libapache2-mod-php7.0 (7.0.27-0+deb9u1) ...
Configurando libxslt1.1:amd64 (1.1.29-2.1) ...
Procesando disparadores para libc-bin (2.24-11+deb9u3) ...
Configurando php7.0-xml (7.0.27-0+deb9u1) ...

Creating config file /etc/php/7.0/mods-available/dom.ini with new version

Creating config file /etc/php/7.0/mods-available/simplexml.ini with new version

Creating config file /etc/php/7.0/mods-available/wddx.ini with new version

Creating config file /etc/php/7.0/mods-available/xml.ini with new version

Creating config file /etc/php/7.0/mods-available/xmlreader.ini with new version

Creating config file /etc/php/7.0/mods-available/xmlwriter.ini with new version

Creating config file /etc/php/7.0/mods-available/xsl.ini with new version
Procesando disparadores para libapache2-mod-php7.0 (7.0.27-0+deb9u1) ...
`

Is possible add this case to troubleshooting?

Bye!

**Comment by andrewhamili** [comment]
Do you have php-xml installed?

**Comment by SNerone** [comment]
Has anyone fixed this issue or could provide a fix for me as I have the same issue.

**Comment by Ymil** [comment]
Hi Snerone. You use linux?? This issue have the resolusion:
https://github.com/klaussilveira/gitlist/issues/791#issuecomment-430772528

Bye .!
